server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://mongo-accounts:27017/accounts_db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    appname: account-service
    instance-id: account-service
    prefer-ip-address: true
